"""empty message

Revision ID: 61963f01f802
Revises: 
Create Date: 2021-11-27 23:42:28.625857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61963f01f802'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user', sa.String(length=20), nullable=False, comment='用户名,唯一不可重复'),
    sa.Column('msg', sa.String(length=255), nullable=True, comment='需要传递的消息'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
