"""empty message

Revision ID: a3a760f7a4c8
Revises: 61963f01f802
Create Date: 2021-12-03 23:03:53.396537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3a760f7a4c8'
down_revision = '61963f01f802'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('file_name', sa.String(length=255), nullable=True, comment='上传的文件名称'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'file_name')
    # ### end Alembic commands ###
